In [1]:
from constants import *

In [2]:
import matplotlib.pyplot as plt
import glob
import pandas as pd
import os
import numpy as np

In [3]:
shapes_mel = []

counter = 0
files = list(map(lambda x: x.split('/')[-1], glob.glob(os.path.join(TRAIN_PATH, 'mel', '*.' + IMG_FORMAT))))
for img in files:
    counter += 1
    shapes_mel.append(plt.imread(os.path.join('..', 'ISIC-2019', 'ISIC_2019_Training_Input', img)).shape)

In [4]:
shapes_non_mel = []

counter = 0
files = list(map(lambda x: x.split('/')[-1], glob.glob(os.path.join(TRAIN_PATH, 'other', '*.' + IMG_FORMAT))))
for img in files:
    counter += 1
    if str.isnumeric(img[0]) and img[1] == '_':
        img = img[2:]
    shapes_non_mel.append(plt.imread(os.path.join('..', 'ISIC-2019', 'ISIC_2019_Training_Input', img)).shape)

# New pre-processing

In [6]:
m_values, m_counts = np.unique(ar=shapes_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)
nm_values, nm_counts = np.unique(ar=shapes_non_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)

In [8]:
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  761
[ 680 1024    3]  ->  154
[1024 1024    3]  ->  2067


In [9]:
total = sum(m_counts)
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  25.5%
[ 680 1024    3]  ->  5.2%
[1024 1024    3]  ->  69.3%


In [10]:
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  4793
[ 680 1024    3]  ->  636
[1024 1024    3]  ->  5222


In [11]:
total = sum(nm_counts)
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  45.0%
[ 680 1024    3]  ->  6.0%
[1024 1024    3]  ->  49.0%


# Before (Old)

In [26]:
m_values, m_counts = np.unique(ar=shapes_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)

array([ 761,    2,    1,    9,    1,    1,    1,    1,    2,    7,    1,
         10,  154,    9,    1,    8,    4,    5,    8,    1,    1,    1,
          1,    3,    1,    1,    2,  133,    7,    1,    1,    1, 2067])

In [27]:
nm_values, nm_counts = np.unique(ar=shapes_non_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)

array([4793,    2,    3,    1,    1,   33,    1,    1,    1,    1,    1,
          1,    1,    1,    1,    3,    5,    2,    1,    1,   11,   19,
         10,   41,    1,  636,   48,    1,  117,   22,   19,   91,   10,
          2,    1,    2,    1,    1,    1,    1,    1,    1,    1,    8,
          1,    1,    7,    2,    1,    1,    3,   59,   15,    2,  420,
          1,    1,   31,    1,    1,    1,    1,    1,    1, 5222])

In [38]:
total = sum(m_counts)
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  23.7%
[542 722   3]  ->  0.1%
[545 722   3]  ->  0.0%
[576 767   3]  ->  0.3%
[602 639   3]  ->  0.0%
[640 964   3]  ->  0.0%
[649 965   3]  ->  0.0%
[674 962   3]  ->  0.0%
[ 674 1024    3]  ->  0.1%
[ 677 1024    3]  ->  0.2%
[ 678 1024    3]  ->  0.0%
[ 679 1024    3]  ->  0.3%
[ 680 1024    3]  ->  4.8%
[ 681 1024    3]  ->  0.3%
[ 682 1016    3]  ->  0.0%
[ 682 1024    3]  ->  0.2%
[ 683 1024    3]  ->  0.1%
[ 684 1024    3]  ->  0.2%
[ 685 1024    3]  ->  0.2%
[ 686 1024    3]  ->  0.0%
[ 687 1024    3]  ->  0.0%
[ 688 1024    3]  ->  0.0%
[ 689 1024    3]  ->  0.0%
[719 824   3]  ->  0.1%
[720 964   3]  ->  0.0%
[724 960   3]  ->  0.0%
[ 767 1022    3]  ->  0.1%
[ 768 1024    3]  ->  4.1%
[802 919   3]  ->  0.2%
[ 861 1024    3]  ->  0.0%
[ 878 1024    3]  ->  0.0%
[1024  857    3]  ->  0.0%
[1024 1024    3]  ->  64.5%


In [1]:
23.7 + 4.8 + 64.5

93.0

In [39]:
total = sum(nm_counts)
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', '{:.1%}'.format(count/total))

[450 600   3]  ->  41.1%
[542 718   3]  ->  0.0%
[542 722   3]  ->  0.0%
[542 725   3]  ->  0.0%
[543 722   3]  ->  0.0%
[576 767   3]  ->  0.3%
[638 959   3]  ->  0.0%
[639 959   3]  ->  0.0%
[640 957   3]  ->  0.0%
[641 962   3]  ->  0.0%
[ 669 1024    3]  ->  0.0%
[671 962   3]  ->  0.0%
[ 671 1024    3]  ->  0.0%
[672 964   3]  ->  0.0%
[ 672 1024    3]  ->  0.0%
[ 673 1024    3]  ->  0.0%
[674 962   3]  ->  0.0%
[ 674 1024    3]  ->  0.0%
[ 675 1024    3]  ->  0.0%
[676 962   3]  ->  0.0%
[ 676 1024    3]  ->  0.1%
[ 677 1024    3]  ->  0.2%
[ 678 1024    3]  ->  0.1%
[ 679 1024    3]  ->  0.4%
[680 853   3]  ->  0.0%
[ 680 1024    3]  ->  5.4%
[ 681 1024    3]  ->  0.4%
[682 796   3]  ->  0.0%
[ 682 1024    3]  ->  1.0%
[ 683 1024    3]  ->  0.2%
[ 684 1024    3]  ->  0.2%
[ 685 1024    3]  ->  0.8%
[ 686 1024    3]  ->  0.1%
[ 689 1024    3]  ->  0.0%
[ 690 1024    3]  ->  0.0%
[ 692 1024    3]  ->  0.0%
[ 704 1007    3]  ->  0.0%
[ 710 1024    3]  ->  0.0%
[ 711 1007    3]  -> 

In [2]:
41.1 + 5.4 +  44.7

91.2