In [1]:
from constants import *

In [13]:
import matplotlib.pyplot as plt
import glob
import pandas as pd
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1. Check shapes by all classes

In [11]:
df_2019 = pd.read_csv('../ISIC-2019/ISIC_2019_Training_Metadata.csv')

df_2019_target = pd.read_csv('../ISIC-2019/ISIC_2019_Training_GroundTruth.csv', 
                             index_col='image').drop('UNK', axis=1)
df_2019_target = df_2019_target.astype(int)

df = pd.merge(left=df_2019_target, right=df_2019[['image', 'lesion_id']], on='image', how='left')

In [15]:
class_2_shapes = {}
for disease_class in CLASSES_2019:
    df_disease = df[df[disease_class.upper()] == 1]
    
    tmp = []
    for img in df_disease.image:
        tmp.append(plt.imread(os.path.join('..', 'ISIC-2019', 'ISIC_2019_Training_Input', img + '.' + IMG_FORMAT)).shape)

    class_2_shapes[disease_class] = tmp

In [20]:
for key, item in class_2_shapes.items():
    print(key)
    values, counts = np.unique(ar=np.array(class_2_shapes[key]), return_counts=True, axis=0)
    for v, c in zip(values, counts):
        print(v, ' -> ', c)
    print('-' * 50)

ak
[450 600   3]  ->  130
[1024 1024    3]  ->  737
--------------------------------------------------
bcc
[450 600   3]  ->  514
[1024 1024    3]  ->  2809
--------------------------------------------------
bkl
[450 600   3]  ->  1099
[ 671 1024    3]  ->  1
[ 677 1024    3]  ->  1
[ 678 1024    3]  ->  1
[ 679 1024    3]  ->  5
[ 680 1024    3]  ->  233
[ 681 1024    3]  ->  6
[ 682 1024    3]  ->  8
[ 683 1024    3]  ->  3
[ 684 1024    3]  ->  3
[ 685 1024    3]  ->  40
[ 686 1024    3]  ->  2
[ 704 1007    3]  ->  1
[ 717 1017    3]  ->  1
[ 764 1024    3]  ->  81
[ 768 1024    3]  ->  1
[1024 1024    3]  ->  1138
--------------------------------------------------
df
[450 600   3]  ->  115
[1024 1024    3]  ->  124
--------------------------------------------------
nv
[450 600   3]  ->  6705
[542 718   3]  ->  2
[542 722   3]  ->  4
[542 724   3]  ->  1
[542 725   3]  ->  1
[543 722   3]  ->  1
[576 767   3]  ->  54
[626 949   3]  ->  1
[634 959   3]  ->  1
[638 959   3]  ->  1
[6

## 2. Check shapes by binary classes

In [3]:
shapes_mel = []

counter = 0
files = list(map(lambda x: x.split('/')[-1], glob.glob(os.path.join(TRAIN_PATH, 'mel', '*.' + IMG_FORMAT))))
for img in files:
    counter += 1
    shapes_mel.append(plt.imread(os.path.join('..', 'ISIC-2019', 'ISIC_2019_Training_Input', img)).shape)

In [4]:
shapes_non_mel = []

counter = 0
files = list(map(lambda x: x.split('/')[-1], glob.glob(os.path.join(TRAIN_PATH, 'other', '*.' + IMG_FORMAT))))
for img in files:
    counter += 1
    if str.isnumeric(img[0]) and img[1] == '_':
        img = img[2:]
    shapes_non_mel.append(plt.imread(os.path.join('..', 'ISIC-2019', 'ISIC_2019_Training_Input', img)).shape)

In [5]:
m_values, m_counts = np.unique(ar=shapes_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)
nm_values, nm_counts = np.unique(ar=shapes_non_mel, return_index=False, return_inverse=False, return_counts=True, axis=0)

## 3. New pre-processing

In [8]:
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  761
[ 680 1024    3]  ->  154
[1024 1024    3]  ->  2067


In [9]:
total = sum(m_counts)
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  25.5%
[ 680 1024    3]  ->  5.2%
[1024 1024    3]  ->  69.3%


In [10]:
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  4793
[ 680 1024    3]  ->  636
[1024 1024    3]  ->  5222


In [11]:
total = sum(nm_counts)
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  45.0%
[ 680 1024    3]  ->  6.0%
[1024 1024    3]  ->  49.0%


## 4. Before (Old)

In [6]:
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  761
[542 722   3]  ->  2
[545 722   3]  ->  1
[576 767   3]  ->  9
[602 639   3]  ->  1
[640 964   3]  ->  1
[649 965   3]  ->  1
[674 962   3]  ->  1
[ 674 1024    3]  ->  2
[ 677 1024    3]  ->  7
[ 678 1024    3]  ->  1
[ 679 1024    3]  ->  10
[ 680 1024    3]  ->  154
[ 681 1024    3]  ->  9
[ 682 1016    3]  ->  1
[ 682 1024    3]  ->  8
[ 683 1024    3]  ->  4
[ 684 1024    3]  ->  5
[ 685 1024    3]  ->  8
[ 686 1024    3]  ->  1
[ 687 1024    3]  ->  1
[ 688 1024    3]  ->  1
[ 689 1024    3]  ->  1
[719 824   3]  ->  3
[720 964   3]  ->  1
[724 960   3]  ->  1
[ 767 1022    3]  ->  2
[ 768 1024    3]  ->  133
[802 919   3]  ->  7
[ 861 1024    3]  ->  1
[ 878 1024    3]  ->  1
[1024  857    3]  ->  1
[1024 1024    3]  ->  2067


In [7]:
total = sum(m_counts)
for value, count in zip(m_values, m_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  23.7%
[542 722   3]  ->  0.1%
[545 722   3]  ->  0.0%
[576 767   3]  ->  0.3%
[602 639   3]  ->  0.0%
[640 964   3]  ->  0.0%
[649 965   3]  ->  0.0%
[674 962   3]  ->  0.0%
[ 674 1024    3]  ->  0.1%
[ 677 1024    3]  ->  0.2%
[ 678 1024    3]  ->  0.0%
[ 679 1024    3]  ->  0.3%
[ 680 1024    3]  ->  4.8%
[ 681 1024    3]  ->  0.3%
[ 682 1016    3]  ->  0.0%
[ 682 1024    3]  ->  0.2%
[ 683 1024    3]  ->  0.1%
[ 684 1024    3]  ->  0.2%
[ 685 1024    3]  ->  0.2%
[ 686 1024    3]  ->  0.0%
[ 687 1024    3]  ->  0.0%
[ 688 1024    3]  ->  0.0%
[ 689 1024    3]  ->  0.0%
[719 824   3]  ->  0.1%
[720 964   3]  ->  0.0%
[724 960   3]  ->  0.0%
[ 767 1022    3]  ->  0.1%
[ 768 1024    3]  ->  4.1%
[802 919   3]  ->  0.2%
[ 861 1024    3]  ->  0.0%
[ 878 1024    3]  ->  0.0%
[1024  857    3]  ->  0.0%
[1024 1024    3]  ->  64.5%


In [8]:
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', count)

[450 600   3]  ->  4793
[542 718   3]  ->  2
[542 722   3]  ->  3
[542 725   3]  ->  1
[543 722   3]  ->  1
[576 767   3]  ->  33
[638 959   3]  ->  1
[639 959   3]  ->  1
[640 957   3]  ->  1
[641 962   3]  ->  1
[ 669 1024    3]  ->  1
[671 962   3]  ->  1
[ 671 1024    3]  ->  1
[672 964   3]  ->  1
[ 672 1024    3]  ->  1
[ 673 1024    3]  ->  3
[674 962   3]  ->  5
[ 674 1024    3]  ->  2
[ 675 1024    3]  ->  1
[676 962   3]  ->  1
[ 676 1024    3]  ->  11
[ 677 1024    3]  ->  19
[ 678 1024    3]  ->  10
[ 679 1024    3]  ->  41
[680 853   3]  ->  1
[ 680 1024    3]  ->  636
[ 681 1024    3]  ->  48
[682 796   3]  ->  1
[ 682 1024    3]  ->  117
[ 683 1024    3]  ->  22
[ 684 1024    3]  ->  19
[ 685 1024    3]  ->  91
[ 686 1024    3]  ->  10
[ 689 1024    3]  ->  2
[ 690 1024    3]  ->  1
[ 692 1024    3]  ->  2
[ 704 1007    3]  ->  1
[ 710 1024    3]  ->  1
[ 711 1007    3]  ->  1
[ 711 1008    3]  ->  1
[ 711 1024    3]  ->  1
[ 713 1011    3]  ->  1
[ 715 1024    3]  ->  1

In [9]:
total = sum(nm_counts)
for value, count in zip(nm_values, nm_counts):
    print(value, ' -> ', '{:.1%}'.format(count / total))

[450 600   3]  ->  41.1%
[542 718   3]  ->  0.0%
[542 722   3]  ->  0.0%
[542 725   3]  ->  0.0%
[543 722   3]  ->  0.0%
[576 767   3]  ->  0.3%
[638 959   3]  ->  0.0%
[639 959   3]  ->  0.0%
[640 957   3]  ->  0.0%
[641 962   3]  ->  0.0%
[ 669 1024    3]  ->  0.0%
[671 962   3]  ->  0.0%
[ 671 1024    3]  ->  0.0%
[672 964   3]  ->  0.0%
[ 672 1024    3]  ->  0.0%
[ 673 1024    3]  ->  0.0%
[674 962   3]  ->  0.0%
[ 674 1024    3]  ->  0.0%
[ 675 1024    3]  ->  0.0%
[676 962   3]  ->  0.0%
[ 676 1024    3]  ->  0.1%
[ 677 1024    3]  ->  0.2%
[ 678 1024    3]  ->  0.1%
[ 679 1024    3]  ->  0.4%
[680 853   3]  ->  0.0%
[ 680 1024    3]  ->  5.4%
[ 681 1024    3]  ->  0.4%
[682 796   3]  ->  0.0%
[ 682 1024    3]  ->  1.0%
[ 683 1024    3]  ->  0.2%
[ 684 1024    3]  ->  0.2%
[ 685 1024    3]  ->  0.8%
[ 686 1024    3]  ->  0.1%
[ 689 1024    3]  ->  0.0%
[ 690 1024    3]  ->  0.0%
[ 692 1024    3]  ->  0.0%
[ 704 1007    3]  ->  0.0%
[ 710 1024    3]  ->  0.0%
[ 711 1007    3]  -> 

In [2]:
41.1 + 5.4 +  44.7

91.2